### ISSUE TITLE
Pull requests?

### ISSUE THREAD

**Issue by PBnJK** [gboncoffee/egg#25]
Is this project open for contributions? I see the CONTRIBUTING file, but it doesn't say anything about pull requests... I'd love to try and contribute bugfixes, or maybe a backend like the Z80.

Obrigado!

**Comment by gboncoffee** [comment]
Yes! I'll make it explicity in the CONTRIBUTING file. Currently we're not tracking any known bug, but in the following weeks this semester's students at UFPR are going to start with Assembly, and that's the semester period when bugs start popping out lmao. Regarding backends, Z80 would be great. I have a branch where I started implementing 6502 tho it's development is halted right now, you may want to check it out...

Thanks for the interest ;)

**Comment by PBnJK** [comment]
Alright! Thank you very much :D
